name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the main branch of this repository
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets['GH_PAT'] }}
        ref: master

    # Checkout the "build" branch of this repository
    - name: Checkout build branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets['GH_PAT'] }}
        ref: build

    # Set the local git user config to use the GitHub Actions bot account
    - name: Set local git config user details
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    # Merge this branch into the "build" branch
    - name: Merge into build branch
      run: git merge master

    # Setup some Node.js stuff
    - name: Node.js setup
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Setup GitHub SSH key so we can npm install GitHub repositories (even needed for public ones)
    - name: GitHub SSH setup
      uses: webfactory/ssh-agent@master
      with:
        ssh-private-key: ${{ secrets['GH_SSH'] }}

    # Install NPM dependencies and build
    - name: Install NPM dependencies and build
      run: |
        npm ci
        node cmd.js -c dashboard -s ci
        npm run build

    # Commit newly built files
    - name: Commit built files
      run: |
        git add -f ':(glob)./*/*/dist/**' ':(exclude)node_modules'
        git commit -m "Built files" -a

    # Pushes the built files
    - name: Push built files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets['GH_PAT'] }}
        branch: build
